cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://api.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

  springdoc:
    pathsToMatch: v1/api/**/**
    swagger-ui:
      use-root-path: true